[rospy.client][INFO] 2018-12-04 18:50:23,835: init_node, name[/software_runstop], pid[12741]
[xmlrpc][INFO] 2018-12-04 18:50:23,835: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 18:50:23,835: Started XML-RPC server [http://freight1207:50142/]
[rospy.init][INFO] 2018-12-04 18:50:23,835: ROS Slave URI: [http://freight1207:50142/]
[rospy.impl.masterslave][INFO] 2018-12-04 18:50:23,835: _ready: http://freight1207:50142/
[xmlrpc][INFO] 2018-12-04 18:50:23,836: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 18:50:23,836: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 18:50:23,935: registered with master
[rospy.rosout][INFO] 2018-12-04 18:50:23,936: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 18:50:23,937: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 18:50:23,938: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-12-04 18:50:23,950: topic[/robot_state] adding connection to [http://freight1207:33896/], count 0
[rospy.internal][INFO] 2018-12-04 18:50:24,220: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2018-12-04 18:50:29,110: signal_shutdown [signal-2]
[rospy.internal][INFO] 2018-12-04 18:50:29,113: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-04 18:50:29,113: topic[/robot_state] removing connection to http://freight1207:33896/
[rospy.impl.masterslave][INFO] 2018-12-04 18:50:29,113: signal-2
[rospy.internal][ERROR] 2018-12-04 18:50:29,114: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2018-12-04 18:50:29,217: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-04 18:50:40,079: init_node, name[/software_runstop], pid[12799]
[xmlrpc][INFO] 2018-12-04 18:50:40,079: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-04 18:50:40,079: Started XML-RPC server [http://freight1207:55270/]
[rospy.init][INFO] 2018-12-04 18:50:40,079: ROS Slave URI: [http://freight1207:55270/]
[rospy.impl.masterslave][INFO] 2018-12-04 18:50:40,079: _ready: http://freight1207:55270/
[xmlrpc][INFO] 2018-12-04 18:50:40,080: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-04 18:50:40,080: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-04 18:50:40,180: registered with master
[rospy.rosout][INFO] 2018-12-04 18:50:40,180: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-04 18:50:40,181: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-04 18:50:40,182: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-12-04 18:50:40,194: topic[/joy] adding connection to [http://freight1207:40494/], count 0
[rospy.internal][INFO] 2018-12-04 18:50:40,195: topic[/robot_state] adding connection to [http://freight1207:33896/], count 0
[rospy.internal][INFO] 2018-12-04 18:50:40,442: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-04 18:51:16,818: topic[/enable_software_runstop] adding connection to [http://freight1207:46529/], count 0
[rosout][INFO] 2018-12-04 18:51:16,891: Software runstop waiting for /base_breaker service...
[rosout][INFO] 2018-12-04 18:51:16,909: Server sent response : 
status: 
  name: ''
  state: 0
  current: 0.0469970703125
  temperature: 26.0
  min_rated_current: 0.0
  max_rated_current: 0.0
  max_rated_temperature: 0.0
[rospy.internal][WARNING] 2018-12-04 18:51:25,747: Unknown error initiating TCP/IP socket to freight1207:56125 (http://freight1207:46529/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-04 18:51:25,747: topic[/enable_software_runstop] removing connection to http://freight1207:46529/
[rospy.internal][INFO] 2018-12-04 18:51:31,636: topic[/enable_software_runstop] adding connection to [http://freight1207:57555/], count 0
[rosout][INFO] 2018-12-04 18:51:31,691: Software runstop waiting for /base_breaker service...
[rosout][INFO] 2018-12-04 18:51:31,724: Server sent response : 
status: 
  name: ''
  state: 1
  current: 0.201416015625
  temperature: 26.0
  min_rated_current: 0.0
  max_rated_current: 0.0
  max_rated_temperature: 0.0
[rospy.internal][WARNING] 2018-12-04 18:51:39,714: Unknown error initiating TCP/IP socket to freight1207:46477 (http://freight1207:57555/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-04 18:51:39,714: topic[/enable_software_runstop] removing connection to http://freight1207:57555/
[rospy.internal][INFO] 2018-12-04 18:52:06,808: topic[/enable_software_runstop] adding connection to [http://freight1207:45674/], count 0
[rosout][INFO] 2018-12-04 18:52:06,891: Software runstop waiting for /base_breaker service...
[rosout][INFO] 2018-12-04 18:52:06,909: Server sent response : 
status: 
  name: ''
  state: 0
  current: 0.040283203125
  temperature: 26.0
  min_rated_current: 0.0
  max_rated_current: 0.0
  max_rated_temperature: 0.0
[rospy.internal][WARNING] 2018-12-04 18:52:10,841: Unknown error initiating TCP/IP socket to freight1207:48114 (http://freight1207:45674/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-04 18:52:10,841: topic[/enable_software_runstop] removing connection to http://freight1207:45674/
[rospy.internal][INFO] 2018-12-04 18:52:26,527: topic[/enable_software_runstop] adding connection to [http://freight1207:53377/], count 0
[rosout][INFO] 2018-12-04 18:52:26,591: Software runstop waiting for /base_breaker service...
[rosout][INFO] 2018-12-04 18:52:26,624: Server sent response : 
status: 
  name: ''
  state: 1
  current: 0.0604248046875
  temperature: 26.0
  min_rated_current: 0.0
  max_rated_current: 0.0
  max_rated_temperature: 0.0
[rospy.internal][WARNING] 2018-12-04 18:52:38,150: Unknown error initiating TCP/IP socket to freight1207:40326 (http://freight1207:53377/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-04 18:52:38,151: topic[/enable_software_runstop] removing connection to http://freight1207:53377/
[rospy.core][INFO] 2018-12-04 18:54:06,405: signal_shutdown [signal-2]
[rospy.internal][INFO] 2018-12-04 18:54:06,408: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2018-12-04 18:54:06,408: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-04 18:54:06,408: topic[/robot_state] removing connection to http://freight1207:33896/
[rospy.internal][INFO] 2018-12-04 18:54:06,408: topic[/joy] removing connection to http://freight1207:40494/
[rospy.impl.masterslave][INFO] 2018-12-04 18:54:06,408: signal-2
[rospy.core][INFO] 2018-12-04 18:54:06,516: signal_shutdown [atexit]
