[rospy.client][INFO] 2020-11-03 03:32:39,771: init_node, name[/rostful_server], pid[4888]
[xmlrpc][INFO] 2020-11-03 03:32:39,771: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 03:32:39,772: Started XML-RPC server [http://freight1207:56583/]
[rospy.init][INFO] 2020-11-03 03:32:39,772: ROS Slave URI: [http://freight1207:56583/]
[rospy.impl.masterslave][INFO] 2020-11-03 03:32:39,772: _ready: http://freight1207:56583/
[xmlrpc][INFO] 2020-11-03 03:32:39,772: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 03:32:39,772: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 03:32:39,872: registered with master
[rospy.rosout][INFO] 2020-11-03 03:32:39,872: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 03:32:39,874: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 03:32:39,875: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 03:32:39,879: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 03:32:40,130: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-11-03 03:32:40,926: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 03:32:40,932: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rospy.internal][INFO] 2020-11-03 03:32:40,938: topic[/enable_software_runstop] adding connection to [http://freight1207:56583/], count 0
[rospy.internal][INFO] 2020-11-03 03:32:40,939: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rosout][INFO] 2020-11-03 03:33:11,163: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 03:33:11,163: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 03:33:11,166: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 03:33:11,166: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 03:33:11,166: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 03:33:11,167: topic[/enable_software_runstop] removing connection to http://freight1207:56583/
[rospy.impl.masterslave][INFO] 2020-11-03 03:33:11,167: Closing
[rospy.core][INFO] 2020-11-03 03:33:11,331: signal_shutdown [atexit]
[rospy.client][INFO] 2020-11-03 03:33:37,707: init_node, name[/rostful_server], pid[5883]
[xmlrpc][INFO] 2020-11-03 03:33:37,707: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-03 03:33:37,708: Started XML-RPC server [http://freight1207:50370/]
[rospy.init][INFO] 2020-11-03 03:33:37,708: ROS Slave URI: [http://freight1207:50370/]
[rospy.impl.masterslave][INFO] 2020-11-03 03:33:37,708: _ready: http://freight1207:50370/
[xmlrpc][INFO] 2020-11-03 03:33:37,708: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-03 03:33:37,708: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-03 03:33:37,808: registered with master
[rospy.rosout][INFO] 2020-11-03 03:33:37,808: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-03 03:33:37,810: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-03 03:33:37,811: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-03 03:33:37,816: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-03 03:33:38,108: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,875: topic[/current/pose] adding connection to [http://freight1207:50370/], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,876: topic[/enable_software_runstop] adding connection to [http://freight1207:50370/], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,877: topic[/local_control/cancel] adding connection to [http://freight1207:50370/], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,878: topic[/local_control/initialpose] adding connection to [http://freight1207:50370/], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,878: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,879: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,879: topic[/local_control/goto] adding connection to [http://freight1207:50370/], count 0
[rosout][INFO] 2020-11-03 03:33:38,880: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-03 03:33:38,880: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,881: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,881: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-03 03:33:38,945: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2020-11-03 03:33:41,239: topic[/current/pose] adding connection to [http://freight1207:38565/], count 1
[rospy.internal][INFO] 2020-11-03 03:33:41,416: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-03 03:33:41,416: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2020-11-03 03:33:41,416: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rosout][WARNING] 2020-11-03 03:36:09,078: publishing data: True to topic /enable_software_runstop
[rospy.internal][WARNING] 2020-11-03 03:37:57,347: Unknown error initiating TCP/IP socket to freight1207:46253 (http://freight1207:38565/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-11-03 03:37:57,347: topic[/current/pose] removing connection to http://freight1207:38565/
[rosout][INFO] 2020-11-03 03:37:58,663: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-03 03:37:58,663: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-03 03:37:58,667: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 03:37:58,667: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-03 03:37:58,667: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 03:37:58,667: Unable to initiate TCP/IP socket to freight1207:53662 (http://freight1207:50370/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 03:37:58,667: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-03 03:37:58,668: Unable to initiate TCP/IP socket to freight1207:53662 (http://freight1207:50370/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 03:37:58,668: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-03 03:37:58,668: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-03 03:37:58,668: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-03 03:37:58,668: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 03:37:58,668: Unable to initiate TCP/IP socket to freight1207:53662 (http://freight1207:50370/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 03:37:58,669: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-11-03 03:37:58,669: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-03 03:37:58,669: Unable to initiate TCP/IP socket to freight1207:53662 (http://freight1207:50370/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 03:37:58,669: topic[/enable_software_runstop] removing connection to http://freight1207:50370/
[rospy.internal][ERROR] 2020-11-03 03:37:58,669: Unable to initiate TCP/IP socket to freight1207:53662 (http://freight1207:50370/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-03 03:37:58,669: topic[/local_control/initialpose] removing connection to http://freight1207:50370/
[rospy.internal][INFO] 2020-11-03 03:37:58,670: topic[/local_control/goto] removing connection to http://freight1207:50370/
[rospy.internal][INFO] 2020-11-03 03:37:58,670: topic[/local_control/cancel] removing connection to http://freight1207:50370/
[rospy.internal][INFO] 2020-11-03 03:37:58,670: topic[/current/pose] removing connection to http://freight1207:50370/
[rospy.impl.masterslave][INFO] 2020-11-03 03:37:58,670: Closing
[rospy.core][INFO] 2020-11-03 03:37:58,773: signal_shutdown [atexit]
