[rospy.client][INFO] 2020-11-04 17:32:15,809: init_node, name[/say_24336_1604539935788], pid[24336]
[xmlrpc][INFO] 2020-11-04 17:32:15,810: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-04 17:32:15,810: Started XML-RPC server [http://freight1207:59841/]
[rospy.init][INFO] 2020-11-04 17:32:15,810: ROS Slave URI: [http://freight1207:59841/]
[rospy.impl.masterslave][INFO] 2020-11-04 17:32:15,810: _ready: http://freight1207:59841/
[xmlrpc][INFO] 2020-11-04 17:32:15,810: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-04 17:32:15,810: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-04 17:32:15,910: registered with master
[rospy.rosout][INFO] 2020-11-04 17:32:15,910: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-04 17:32:15,912: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-04 17:32:15,913: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-04 17:32:15,925: topic[/sound_play/feedback] adding connection to [http://freight1207:37705/], count 0
[rospy.internal][INFO] 2020-11-04 17:32:15,926: topic[/sound_play/result] adding connection to [http://freight1207:37705/], count 0
[rospy.internal][INFO] 2020-11-04 17:32:15,926: topic[/sound_play/status] adding connection to [http://freight1207:37705/], count 0
[rospy.internal][INFO] 2020-11-04 17:32:16,049: topic[/robotsound] adding connection to [/sound_play], count 0
[rospy.internal][INFO] 2020-11-04 17:32:16,050: topic[/sound_play/goal] adding connection to [/sound_play], count 0
[rospy.internal][INFO] 2020-11-04 17:32:16,050: topic[/sound_play/cancel] adding connection to [/sound_play], count 0
[rospy.internal][INFO] 2020-11-04 17:32:16,207: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-04 17:32:17,929: topic[/odom] adding connection to [http://freight1207:54641/], count 0
[rospy.internal][ERROR] 2020-11-04 18:48:37,738: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 698, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 4] Interrupted system call

[rospy.internal][WARNING] 2020-11-04 18:48:37,738: Unknown error initiating TCP/IP socket to freight1207:47521 (http://freight1207:54641/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-11-04 18:48:37,738: topic[/odom] removing connection to http://freight1207:54641/
[rosout][WARNING] 2020-11-04 18:48:37,745: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2020-11-04 18:48:37,745: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2020-11-04 18:48:37,772: Unknown error initiating TCP/IP socket to freight1207:43705 (http://freight1207:37705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-11-04 18:48:37,772: topic[/sound_play/feedback] removing connection to http://freight1207:37705/
[rospy.internal][WARNING] 2020-11-04 18:48:37,772: Unknown error initiating TCP/IP socket to freight1207:43705 (http://freight1207:37705/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-11-04 18:48:37,772: topic[/sound_play/result] removing connection to http://freight1207:37705/
