[rospy.client][INFO] 2020-11-05 00:28:31,589: init_node, name[/rostful_server], pid[5770]
[xmlrpc][INFO] 2020-11-05 00:28:31,589: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-05 00:28:31,589: Started XML-RPC server [http://freight1207:40640/]
[rospy.init][INFO] 2020-11-05 00:28:31,589: ROS Slave URI: [http://freight1207:40640/]
[rospy.impl.masterslave][INFO] 2020-11-05 00:28:31,589: _ready: http://freight1207:40640/
[xmlrpc][INFO] 2020-11-05 00:28:31,590: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-05 00:28:31,590: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-05 00:28:31,690: registered with master
[rospy.rosout][INFO] 2020-11-05 00:28:31,690: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-05 00:28:31,691: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-05 00:28:31,692: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-05 00:28:31,696: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-05 00:28:31,906: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-11-05 00:28:32,734: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-05 00:28:32,756: topic[/enable_software_runstop] adding connection to [http://freight1207:40640/], count 0
[rospy.internal][INFO] 2020-11-05 00:28:32,757: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-05 00:28:32,772: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-11-05 00:29:21,206: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-05 00:29:21,207: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-05 00:29:21,209: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-05 00:29:21,209: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-05 00:29:21,209: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-11-05 00:29:21,209: topic[/enable_software_runstop] removing connection to http://freight1207:40640/
[rospy.impl.masterslave][INFO] 2020-11-05 00:29:21,209: Closing
[rospy.internal][ERROR] 2020-11-05 00:29:21,210: Unable to initiate TCP/IP socket to freight1207:45402 (http://freight1207:40640/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-11-05 00:29:21,341: signal_shutdown [atexit]
[rospy.client][INFO] 2020-11-05 00:29:23,148: init_node, name[/rostful_server], pid[6115]
[xmlrpc][INFO] 2020-11-05 00:29:23,148: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-05 00:29:23,149: Started XML-RPC server [http://freight1207:51098/]
[rospy.impl.masterslave][INFO] 2020-11-05 00:29:23,149: _ready: http://freight1207:51098/
[rospy.init][INFO] 2020-11-05 00:29:23,149: ROS Slave URI: [http://freight1207:51098/]
[xmlrpc][INFO] 2020-11-05 00:29:23,149: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-05 00:29:23,149: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-05 00:29:23,249: registered with master
[rospy.rosout][INFO] 2020-11-05 00:29:23,249: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-05 00:29:23,251: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-05 00:29:23,252: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-11-05 00:29:23,256: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-11-05 00:29:23,478: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,316: topic[/current/pose] adding connection to [http://freight1207:45841/], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,318: topic[/current/pose] adding connection to [http://freight1207:51098/], count 1
[rospy.internal][INFO] 2020-11-05 00:29:24,319: topic[/enable_software_runstop] adding connection to [http://freight1207:51098/], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,320: topic[/local_control/cancel] adding connection to [http://freight1207:51098/], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,321: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,321: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,322: topic[/local_control/initialpose] adding connection to [http://freight1207:51098/], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,323: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,323: topic[/local_control/goto] adding connection to [http://freight1207:51098/], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,324: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rosout][INFO] 2020-11-05 00:29:24,324: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-11-05 00:29:24,324: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-11-05 00:29:24,346: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2020-11-05 00:29:24,482: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2020-11-05 00:29:24,482: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-11-05 00:29:24,483: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rosout][WARNING] 2020-11-05 00:29:28,640: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:34,827: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:35,774: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:36,663: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:37,221: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:37,814: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:39,734: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][WARNING] 2020-11-05 00:29:42,906: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -10.1354064775
    locationY: -2.07501086452
    orientation: 0.555997582506
  - 
    locationX: -9.54077873636
    locationY: -0.669338153814
    orientation: 0.55274748647 to topic /local_control/goto
[rosout][INFO] 2020-11-05 00:30:14,175: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-11-05 00:30:14,176: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-11-05 00:30:14,179: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-05 00:30:14,179: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-11-05 00:30:14,179: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-05 00:30:14,180: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-11-05 00:30:14,180: Unable to initiate TCP/IP socket to freight1207:41052 (http://freight1207:51098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-05 00:30:14,180: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2020-11-05 00:30:14,180: Unable to initiate TCP/IP socket to freight1207:41052 (http://freight1207:51098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-05 00:30:14,180: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-11-05 00:30:14,181: Unable to initiate TCP/IP socket to freight1207:41052 (http://freight1207:51098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-05 00:30:14,181: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-11-05 00:30:14,181: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-05 00:30:14,181: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-11-05 00:30:14,181: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/enable_software_runstop] removing connection to http://freight1207:51098/
[rospy.internal][ERROR] 2020-11-05 00:30:14,182: Unable to initiate TCP/IP socket to freight1207:41052 (http://freight1207:51098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/local_control/initialpose] removing connection to http://freight1207:51098/
[rospy.internal][ERROR] 2020-11-05 00:30:14,182: Unable to initiate TCP/IP socket to freight1207:41052 (http://freight1207:51098/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/local_control/goto] removing connection to http://freight1207:51098/
[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/local_control/cancel] removing connection to http://freight1207:51098/
[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/current/pose] removing connection to http://freight1207:45841/
[rospy.internal][INFO] 2020-11-05 00:30:14,182: topic[/current/pose] removing connection to http://freight1207:51098/
[rospy.impl.masterslave][INFO] 2020-11-05 00:30:14,182: Closing
[rospy.core][INFO] 2020-11-05 00:30:14,298: signal_shutdown [atexit]
