[rospy.client][INFO] 2020-10-28 22:34:32,091: init_node, name[/rostful_server], pid[4416]
[xmlrpc][INFO] 2020-10-28 22:34:32,091: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-28 22:34:32,091: Started XML-RPC server [http://freight1207:53756/]
[rospy.init][INFO] 2020-10-28 22:34:32,091: ROS Slave URI: [http://freight1207:53756/]
[rospy.impl.masterslave][INFO] 2020-10-28 22:34:32,091: _ready: http://freight1207:53756/
[xmlrpc][INFO] 2020-10-28 22:34:32,092: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-28 22:34:32,092: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-28 22:34:32,191: registered with master
[rospy.rosout][INFO] 2020-10-28 22:34:32,192: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-28 22:34:32,193: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-28 22:34:32,194: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-28 22:34:32,198: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-28 22:34:32,426: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-10-28 22:34:33,257: topic[/enable_software_runstop] adding connection to [http://freight1207:53756/], count 0
[rospy.internal][INFO] 2020-10-28 22:34:33,258: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-28 22:34:33,273: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-10-28 22:34:43,235: rostful_server: Started server on port 8080
[rosout][INFO] 2020-10-28 22:36:33,890: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-28 22:36:33,890: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-28 22:36:33,893: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-28 22:36:33,893: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-28 22:36:33,893: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-10-28 22:36:33,894: topic[/enable_software_runstop] removing connection to http://freight1207:53756/
[rospy.impl.masterslave][INFO] 2020-10-28 22:36:33,894: Closing
[rospy.internal][ERROR] 2020-10-28 22:36:33,895: Unable to initiate TCP/IP socket to freight1207:53255 (http://freight1207:53756/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-10-28 22:36:34,001: signal_shutdown [atexit]
[rospy.client][INFO] 2020-10-28 22:45:04,576: init_node, name[/rostful_server], pid[4537]
[xmlrpc][INFO] 2020-10-28 22:45:04,576: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-28 22:45:04,577: Started XML-RPC server [http://freight1207:44879/]
[rospy.init][INFO] 2020-10-28 22:45:04,577: ROS Slave URI: [http://freight1207:44879/]
[rospy.impl.masterslave][INFO] 2020-10-28 22:45:04,577: _ready: http://freight1207:44879/
[xmlrpc][INFO] 2020-10-28 22:45:04,577: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-28 22:45:04,577: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-28 22:45:04,677: registered with master
[rospy.rosout][INFO] 2020-10-28 22:45:04,677: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-28 22:45:04,680: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-28 22:45:04,681: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-28 22:45:04,685: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-28 22:45:04,887: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-10-28 22:45:05,726: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-10-28 22:45:05,744: topic[/enable_software_runstop] adding connection to [http://freight1207:44879/], count 0
[rospy.internal][INFO] 2020-10-28 22:45:05,745: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-28 22:45:05,791: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-10-28 22:53:49,053: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-28 22:53:49,054: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-28 22:53:49,056: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-28 22:53:49,056: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-28 22:53:49,056: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-10-28 22:53:49,057: topic[/enable_software_runstop] removing connection to http://freight1207:44879/
[rospy.impl.masterslave][INFO] 2020-10-28 22:53:49,057: Closing
[rospy.internal][ERROR] 2020-10-28 22:53:49,057: Unable to initiate TCP/IP socket to freight1207:54628 (http://freight1207:44879/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-10-28 22:53:49,188: signal_shutdown [atexit]
[rospy.client][INFO] 2020-10-28 22:53:51,179: init_node, name[/rostful_server], pid[5125]
[xmlrpc][INFO] 2020-10-28 22:53:51,180: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-28 22:53:51,180: Started XML-RPC server [http://freight1207:44193/]
[rospy.init][INFO] 2020-10-28 22:53:51,180: ROS Slave URI: [http://freight1207:44193/]
[rospy.impl.masterslave][INFO] 2020-10-28 22:53:51,180: _ready: http://freight1207:44193/
[xmlrpc][INFO] 2020-10-28 22:53:51,180: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-28 22:53:51,181: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-28 22:53:51,280: registered with master
[rospy.rosout][INFO] 2020-10-28 22:53:51,281: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-28 22:53:51,282: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-28 22:53:51,283: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-28 22:53:51,287: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-28 22:53:51,499: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-10-28 22:53:52,320: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-10-28 22:53:52,346: topic[/enable_software_runstop] adding connection to [http://freight1207:44193/], count 0
[rospy.internal][INFO] 2020-10-28 22:53:52,348: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-28 22:53:52,412: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-10-28 22:55:42,362: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-28 22:55:42,362: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-28 22:55:42,364: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-28 22:55:42,364: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-28 22:55:42,364: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-10-28 22:55:42,365: topic[/enable_software_runstop] removing connection to http://freight1207:44193/
[rospy.impl.masterslave][INFO] 2020-10-28 22:55:42,365: Closing
[rospy.internal][ERROR] 2020-10-28 22:55:42,365: Unable to initiate TCP/IP socket to freight1207:60360 (http://freight1207:44193/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2020-10-28 22:55:42,472: signal_shutdown [atexit]
[rospy.client][INFO] 2020-10-29 00:35:16,118: init_node, name[/rostful_server], pid[8411]
[xmlrpc][INFO] 2020-10-29 00:35:16,118: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-29 00:35:16,118: Started XML-RPC server [http://freight1207:40396/]
[rospy.init][INFO] 2020-10-29 00:35:16,118: ROS Slave URI: [http://freight1207:40396/]
[rospy.impl.masterslave][INFO] 2020-10-29 00:35:16,118: _ready: http://freight1207:40396/
[xmlrpc][INFO] 2020-10-29 00:35:16,119: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-29 00:35:16,119: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-29 00:35:16,219: registered with master
[rospy.rosout][INFO] 2020-10-29 00:35:16,219: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-29 00:35:16,220: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-29 00:35:16,221: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-29 00:35:16,225: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-29 00:35:16,517: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2020-10-29 00:35:17,277: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-10-29 00:35:17,286: topic[/current/pose] adding connection to [http://freight1207:40396/], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,287: topic[/local_control/initialpose] adding connection to [http://freight1207:40396/], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,288: topic[/local_control/cancel] adding connection to [http://freight1207:40396/], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,289: topic[/enable_software_runstop] adding connection to [http://freight1207:40396/], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,290: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,291: topic[/local_control/goto] adding connection to [http://freight1207:40396/], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,291: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,292: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,292: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,292: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 00:35:17,331: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rosout][INFO] 2020-10-29 00:41:42,687: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-29 00:41:42,688: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-29 00:41:42,691: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 00:41:42,691: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-29 00:41:42,691: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 00:41:42,692: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-10-29 00:41:42,692: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 00:41:42,692: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 00:41:42,693: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-10-29 00:41:42,693: Unable to initiate TCP/IP socket to freight1207:37960 (http://freight1207:40396/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 00:41:42,693: Unable to initiate TCP/IP socket to freight1207:37960 (http://freight1207:40396/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-29 00:41:42,693: topic[/enable_software_runstop] removing connection to http://freight1207:40396/
[rospy.internal][ERROR] 2020-10-29 00:41:42,693: Unable to initiate TCP/IP socket to freight1207:37960 (http://freight1207:40396/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 00:41:42,694: Unable to initiate TCP/IP socket to freight1207:37960 (http://freight1207:40396/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 00:41:42,694: Unable to initiate TCP/IP socket to freight1207:37960 (http://freight1207:40396/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-29 00:41:42,694: topic[/local_control/initialpose] removing connection to http://freight1207:40396/
[rospy.internal][INFO] 2020-10-29 00:41:42,694: topic[/local_control/goto] removing connection to http://freight1207:40396/
[rospy.internal][INFO] 2020-10-29 00:41:42,694: topic[/local_control/cancel] removing connection to http://freight1207:40396/
[rospy.internal][INFO] 2020-10-29 00:41:42,694: topic[/current/pose] removing connection to http://freight1207:40396/
[rospy.impl.masterslave][INFO] 2020-10-29 00:41:42,694: Closing
[rospy.core][INFO] 2020-10-29 00:41:42,802: signal_shutdown [atexit]
[rospy.client][INFO] 2020-10-29 01:58:55,888: init_node, name[/rostful_server], pid[16938]
[xmlrpc][INFO] 2020-10-29 01:58:55,888: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-29 01:58:55,888: Started XML-RPC server [http://freight1207:33045/]
[rospy.init][INFO] 2020-10-29 01:58:55,888: ROS Slave URI: [http://freight1207:33045/]
[rospy.impl.masterslave][INFO] 2020-10-29 01:58:55,888: _ready: http://freight1207:33045/
[xmlrpc][INFO] 2020-10-29 01:58:55,889: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-29 01:58:55,889: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-29 01:58:55,988: registered with master
[rospy.rosout][INFO] 2020-10-29 01:58:55,989: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-29 01:58:55,990: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-29 01:58:55,991: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-29 01:58:55,997: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-29 01:58:56,232: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,038: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rosout][INFO] 2020-10-29 01:58:57,046: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-10-29 01:58:57,055: topic[/current/pose] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,057: topic[/remote_control] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,058: topic[/enable_software_runstop] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,059: topic[/local_control/cancel] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,060: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,061: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,062: topic[/local_control/initialpose] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,062: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rospy.internal][INFO] 2020-10-29 01:58:57,063: topic[/local_control/goto] adding connection to [http://freight1207:33045/], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,063: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,063: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-29 01:58:57,064: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rosout][INFO] 2020-10-29 02:12:14,948: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-29 02:12:14,948: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-29 02:12:14,954: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-29 02:12:14,954: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 02:12:14,954: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 02:12:14,955: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-10-29 02:12:14,955: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 02:12:14,956: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-29 02:12:14,956: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-10-29 02:12:14,957: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 02:12:14,957: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-29 02:12:14,957: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-10-29 02:12:14,958: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 02:12:14,958: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2020-10-29 02:12:14,958: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-29 02:12:14,959: topic[/enable_software_runstop] removing connection to http://freight1207:33045/
[rospy.internal][ERROR] 2020-10-29 02:12:14,959: Unable to initiate TCP/IP socket to freight1207:44321 (http://freight1207:33045/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-29 02:12:14,960: topic[/local_control/goto] removing connection to http://freight1207:33045/
[rospy.internal][INFO] 2020-10-29 02:12:14,960: topic[/local_control/initialpose] removing connection to http://freight1207:33045/
[rospy.internal][INFO] 2020-10-29 02:12:14,960: topic[/remote_control] removing connection to http://freight1207:33045/
[rospy.internal][INFO] 2020-10-29 02:12:14,960: topic[/local_control/cancel] removing connection to http://freight1207:33045/
[rospy.internal][INFO] 2020-10-29 02:12:14,960: topic[/current/pose] removing connection to http://freight1207:33045/
[rospy.impl.masterslave][INFO] 2020-10-29 02:12:14,960: Closing
[rospy.core][INFO] 2020-10-29 02:12:15,068: signal_shutdown [atexit]
