[rospy.client][INFO] 2018-12-16 16:34:40,280: init_node, name[/rostful_server], pid[4202]
[xmlrpc][INFO] 2018-12-16 16:34:40,280: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 16:34:40,280: Started XML-RPC server [http://freight1207:43082/]
[rospy.init][INFO] 2018-12-16 16:34:40,280: ROS Slave URI: [http://freight1207:43082/]
[rospy.impl.masterslave][INFO] 2018-12-16 16:34:40,281: _ready: http://freight1207:43082/
[xmlrpc][INFO] 2018-12-16 16:34:40,281: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 16:34:40,281: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 16:34:40,381: registered with master
[rospy.rosout][INFO] 2018-12-16 16:34:40,381: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 16:34:40,383: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 16:34:40,383: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 16:34:40,387: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 16:34:40,627: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-16 16:34:41,422: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-16 16:34:41,446: topic[/enable_software_runstop] adding connection to [http://freight1207:43082/], count 0
[rospy.internal][INFO] 2018-12-16 16:34:41,448: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:34:41,456: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.client][INFO] 2018-12-16 16:42:05,507: init_node, name[/rostful_server], pid[6388]
[xmlrpc][INFO] 2018-12-16 16:42:05,508: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 16:42:05,508: Started XML-RPC server [http://freight1207:58508/]
[rospy.init][INFO] 2018-12-16 16:42:05,508: ROS Slave URI: [http://freight1207:58508/]
[rospy.impl.masterslave][INFO] 2018-12-16 16:42:05,508: _ready: http://freight1207:58508/
[xmlrpc][INFO] 2018-12-16 16:42:05,508: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 16:42:05,509: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 16:42:05,608: registered with master
[rospy.rosout][INFO] 2018-12-16 16:42:05,608: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 16:42:05,610: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 16:42:05,611: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 16:42:05,615: rostful_server: Delaying the start 1 seconds
[rospy.impl.masterslave][INFO] 2018-12-16 16:42:05,709: external shutdown request from [/master]: new node registered with same name
[rospy.core][INFO] 2018-12-16 16:42:05,709: signal_shutdown [external shutdown request from [/master]: [new node registered with same name]]
[rospy.internal][INFO] 2018-12-16 16:42:05,711: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:05,711: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 16:42:05,711: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-16 16:42:05,712: topic[/enable_software_runstop] removing connection to http://freight1207:43082/
[rospy.internal][ERROR] 2018-12-16 16:42:05,713: Unable to initiate TCP/IP socket to freight1207:50317 (http://freight1207:43082/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 16:42:05,910: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2018-12-16 16:42:06,665: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-16 16:42:06,668: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2018-12-16 16:42:06,669: atexit
[rospy.client][INFO] 2018-12-16 16:42:33,012: init_node, name[/rostful_server], pid[6542]
[xmlrpc][INFO] 2018-12-16 16:42:33,012: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 16:42:33,012: Started XML-RPC server [http://freight1207:41445/]
[rospy.init][INFO] 2018-12-16 16:42:33,013: ROS Slave URI: [http://freight1207:41445/]
[rospy.impl.masterslave][INFO] 2018-12-16 16:42:33,013: _ready: http://freight1207:41445/
[xmlrpc][INFO] 2018-12-16 16:42:33,013: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 16:42:33,013: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 16:42:33,113: registered with master
[rospy.rosout][INFO] 2018-12-16 16:42:33,113: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 16:42:33,115: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 16:42:33,115: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 16:42:33,120: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 16:42:33,320: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,179: topic[/current/pose] adding connection to [http://freight1207:34290/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,180: topic[/current/pose] adding connection to [http://freight1207:41445/], count 1
[rospy.internal][INFO] 2018-12-16 16:42:34,181: topic[/remote_control] adding connection to [http://freight1207:41445/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,183: topic[/enable_software_runstop] adding connection to [http://freight1207:41445/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,183: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,184: topic[/local_control/cancel] adding connection to [http://freight1207:41445/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,186: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,186: topic[/local_control/initialpose] adding connection to [http://freight1207:41445/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,187: topic[/local_control/goto] adding connection to [http://freight1207:41445/], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,187: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,187: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,188: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,188: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:42:34,223: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.core][INFO] 2018-12-16 16:42:34,323: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-16 16:42:34,326: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:34,327: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 16:42:34,327: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:34,327: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-16 16:42:34,327: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:34,328: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:34,328: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 16:42:34,328: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 16:42:34,329: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 16:42:34,329: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 16:42:34,329: topic[/enable_software_runstop] removing connection to http://freight1207:41445/
[rospy.internal][ERROR] 2018-12-16 16:42:34,329: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 16:42:34,329: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 16:42:34,330: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 16:42:34,330: Unable to initiate TCP/IP socket to freight1207:52059 (http://freight1207:41445/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/local_control/goto] removing connection to http://freight1207:41445/
[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/local_control/initialpose] removing connection to http://freight1207:41445/
[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/remote_control] removing connection to http://freight1207:41445/
[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/local_control/cancel] removing connection to http://freight1207:41445/
[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/current/pose] removing connection to http://freight1207:34290/
[rospy.internal][INFO] 2018-12-16 16:42:34,330: topic[/current/pose] removing connection to http://freight1207:41445/
[rospy.impl.masterslave][INFO] 2018-12-16 16:42:34,330: atexit
[rospy.client][INFO] 2018-12-16 16:55:41,920: init_node, name[/rostful_server], pid[7515]
[xmlrpc][INFO] 2018-12-16 16:55:41,920: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 16:55:41,920: Started XML-RPC server [http://freight1207:60706/]
[rospy.init][INFO] 2018-12-16 16:55:41,920: ROS Slave URI: [http://freight1207:60706/]
[rospy.impl.masterslave][INFO] 2018-12-16 16:55:41,921: _ready: http://freight1207:60706/
[xmlrpc][INFO] 2018-12-16 16:55:41,921: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 16:55:41,921: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 16:55:42,021: registered with master
[rospy.rosout][INFO] 2018-12-16 16:55:42,021: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 16:55:42,023: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 16:55:42,023: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 16:55:42,028: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 16:55:42,281: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-16 16:55:43,074: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-16 16:55:43,087: topic[/current/pose] adding connection to [http://freight1207:43922/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,088: topic[/current/pose] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,089: topic[/remote_control] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,090: topic[/enable_software_runstop] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,091: topic[/local_control/cancel] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,092: topic[/local_control/initialpose] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,093: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,094: topic[/local_control/goto] adding connection to [http://freight1207:60706/], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,094: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,094: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,095: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,095: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,095: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 16:55:43,110: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2018-12-16 16:55:43,282: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2018-12-16 16:55:43,282: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 16:55:43,283: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 16:55:43,283: topic[/remote_control] adding connection to [/remote_control], count 1
[rosout][WARNING] 2018-12-16 16:56:04,407: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 16:57:26,838: publishing data: False to topic /enable_software_runstop
[rosout][WARNING] 2018-12-16 16:57:36,315: publishing data: True to topic /enable_software_runstop
[rosout][WARNING] 2018-12-16 16:58:01,551: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 16:58:07,560: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 16:58:15,911: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 0
    locationY: 0
    orientation: 0 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 16:58:36,373: publishing data: False to topic /enable_software_runstop
[rosout][WARNING] 2018-12-16 16:58:49,048: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 0
    locationY: 0
    orientation: 0 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 16:58:59,724: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 16:59:04,067: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 16:59:29,206: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1
    locationY: 1
    orientation: 1
  - 
    locationX: 1
    locationY: 1
    orientation: 1
  - 
    locationX: 1
    locationY: 1
    orientation: 1 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:00:13,457: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:00:19,898: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:03:50,138: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:03:53,196: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:03:59,727: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:02,283: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:04,690: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:07,352: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:10,706: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:13,187: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:16,165: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:18,769: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:21,063: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:25,549: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:28,180: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:30,762: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:31,859: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:32,661: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:34,912: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 17:04:37,236: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:13:11,618: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1
    locationY: 1
    orientation: 1
  - 
    locationX: 1
    locationY: 1
    orientation: 2
  - 
    locationX: 1
    locationY: 1
    orientation: 3 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:23:32,523: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1
    locationY: 1
    orientation: 1
  - 
    locationX: 11
    locationY: 1
    orientation: 1
  - 
    locationX: 1
    locationY: 1
    orientation: 1 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:24:32,659: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1
    locationY: 1
    orientation: 1
  - 
    locationX: 11
    locationY: 1
    orientation: 1 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:24:36,588: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 1
    locationY: 1
    orientation: 1 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:24:44,055: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: 11
    locationY: 11
    orientation: 11 to topic /local_control/goto
[rosout][WARNING] 2018-12-16 17:28:55,806: publishing data: backward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:28:58,664: publishing data: forward to topic /remote_control
[rosout][WARNING] 2018-12-16 17:29:01,480: publishing data: left to topic /remote_control
[rosout][WARNING] 2018-12-16 17:29:03,010: publishing data: right to topic /remote_control
[rosout][WARNING] 2018-12-16 17:29:05,885: publishing data: right to topic /remote_control
[rospy.internal][INFO] 2018-12-16 18:48:18,009: topic[/current/pose] adding connection to [http://freight1207:43389/], count 2
[rospy.internal][WARNING] 2018-12-16 18:48:18,098: Unknown error initiating TCP/IP socket to freight1207:51152 (http://freight1207:43922/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-16 18:48:18,099: topic[/current/pose] removing connection to http://freight1207:43922/
[rospy.internal][WARNING] 2018-12-16 18:48:57,078: Unknown error initiating TCP/IP socket to freight1207:51229 (http://freight1207:43389/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-16 18:48:57,078: topic[/current/pose] removing connection to http://freight1207:43389/
[rospy.internal][INFO] 2018-12-16 18:52:46,349: topic[/current/pose] adding connection to [http://freight1207:52213/], count 1
[rospy.internal][INFO] 2018-12-16 18:52:46,516: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 2
[rospy.internal][INFO] 2018-12-16 18:52:46,517: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-16 18:52:46,517: topic[/local_control/goto] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2018-12-16 18:52:46,517: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][INFO] 2018-12-16 18:52:46,517: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2018-12-16 18:52:46,517: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2018-12-16 18:53:13,040: topic[/current/pose] adding connection to [/rostopic_12312_1545015192908], count 1
[rospy.client][INFO] 2018-12-16 18:54:27,838: init_node, name[/rostful_server], pid[13554]
[xmlrpc][INFO] 2018-12-16 18:54:27,838: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 18:54:27,838: Started XML-RPC server [http://freight1207:44721/]
[rospy.init][INFO] 2018-12-16 18:54:27,838: ROS Slave URI: [http://freight1207:44721/]
[rospy.impl.masterslave][INFO] 2018-12-16 18:54:27,838: _ready: http://freight1207:44721/
[xmlrpc][INFO] 2018-12-16 18:54:27,839: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 18:54:27,839: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 18:54:27,938: registered with master
[rospy.rosout][INFO] 2018-12-16 18:54:27,939: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 18:54:27,940: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 18:54:27,941: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 18:54:27,945: rostful_server: Delaying the start 1 seconds
[rospy.impl.masterslave][INFO] 2018-12-16 18:54:27,958: external shutdown request from [/master]: new node registered with same name
[rospy.core][INFO] 2018-12-16 18:54:27,958: signal_shutdown [external shutdown request from [/master]: [new node registered with same name]]
[rospy.internal][INFO] 2018-12-16 18:54:27,962: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:27,962: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 18:54:27,962: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:27,962: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,962: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2018-12-16 18:54:27,963: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,963: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-16 18:54:27,963: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:27,963: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-16 18:54:27,963: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:27,963: topic[/remote_control] removing connection to /remote_control
[rospy.internal][ERROR] 2018-12-16 18:54:27,964: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,964: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:27,964: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,964: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2018-12-16 18:54:27,964: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,964: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/current/pose] removing connection to /rostopic_12312_1545015192908
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/enable_software_runstop] removing connection to http://freight1207:60706/
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/local_control/goto] removing connection to http://freight1207:60706/
[rospy.internal][ERROR] 2018-12-16 18:54:27,965: Unable to initiate TCP/IP socket to freight1207:43027 (http://freight1207:60706/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/local_control/initialpose] removing connection to http://freight1207:60706/
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/remote_control] removing connection to http://freight1207:60706/
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/local_control/cancel] removing connection to http://freight1207:60706/
[rospy.internal][INFO] 2018-12-16 18:54:27,965: topic[/current/pose] removing connection to http://freight1207:60706/
[rospy.internal][INFO] 2018-12-16 18:54:27,966: topic[/current/pose] removing connection to http://freight1207:52213/
[rospy.internal][INFO] 2018-12-16 18:54:28,161: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,005: topic[/current/pose] adding connection to [http://freight1207:52213/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,006: topic[/current/pose] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,007: topic[/remote_control] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,010: topic[/enable_software_runstop] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,010: topic[/local_control/cancel] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,011: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,012: topic[/local_control/initialpose] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,013: topic[/local_control/goto] adding connection to [http://freight1207:44721/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,013: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,013: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,013: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,014: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,014: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:29,041: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.core][INFO] 2018-12-16 18:54:29,101: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-16 18:54:29,105: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:29,105: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 18:54:29,105: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:29,106: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-16 18:54:29,106: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:29,106: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:29,106: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:29,107: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:29,107: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 18:54:29,107: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 18:54:29,107: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:29,107: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:29,108: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 18:54:29,108: Unable to initiate TCP/IP socket to freight1207:59809 (http://freight1207:44721/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:29,108: topic[/enable_software_runstop] removing connection to http://freight1207:44721/
[rospy.internal][INFO] 2018-12-16 18:54:29,108: topic[/local_control/goto] removing connection to http://freight1207:44721/
[rospy.internal][INFO] 2018-12-16 18:54:29,108: topic[/local_control/initialpose] removing connection to http://freight1207:44721/
[rospy.internal][INFO] 2018-12-16 18:54:29,108: topic[/remote_control] removing connection to http://freight1207:44721/
[rospy.internal][INFO] 2018-12-16 18:54:29,108: topic[/local_control/cancel] removing connection to http://freight1207:44721/
[rospy.internal][INFO] 2018-12-16 18:54:29,109: topic[/current/pose] removing connection to http://freight1207:52213/
[rospy.internal][INFO] 2018-12-16 18:54:29,109: topic[/current/pose] removing connection to http://freight1207:44721/
[rospy.impl.masterslave][INFO] 2018-12-16 18:54:29,109: atexit
[rospy.client][INFO] 2018-12-16 18:54:57,388: init_node, name[/rostful_server], pid[13868]
[xmlrpc][INFO] 2018-12-16 18:54:57,389: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 18:54:57,389: Started XML-RPC server [http://freight1207:35378/]
[rospy.init][INFO] 2018-12-16 18:54:57,389: ROS Slave URI: [http://freight1207:35378/]
[rospy.impl.masterslave][INFO] 2018-12-16 18:54:57,389: _ready: http://freight1207:35378/
[xmlrpc][INFO] 2018-12-16 18:54:57,390: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 18:54:57,390: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 18:54:57,489: registered with master
[rospy.rosout][INFO] 2018-12-16 18:54:57,490: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 18:54:57,491: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 18:54:57,492: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 18:54:57,496: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 18:54:57,705: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,548: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,556: topic[/current/pose] adding connection to [http://freight1207:52213/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,556: topic[/current/pose] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,558: topic[/enable_software_runstop] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,559: topic[/remote_control] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,560: topic[/local_control/cancel] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,561: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rospy.internal][INFO] 2018-12-16 18:54:58,562: topic[/local_control/initialpose] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,562: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,563: topic[/local_control/goto] adding connection to [http://freight1207:35378/], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,563: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,563: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,564: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:54:58,564: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.core][INFO] 2018-12-16 18:54:58,642: signal_shutdown [atexit]
[rospy.internal][INFO] 2018-12-16 18:54:58,646: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 18:54:58,646: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:58,646: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:58,647: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2018-12-16 18:54:58,647: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:58,647: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:58,648: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 18:54:58,648: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:58,648: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 18:54:58,648: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 18:54:58,648: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:58,649: topic[/enable_software_runstop] removing connection to http://freight1207:35378/
[rospy.internal][ERROR] 2018-12-16 18:54:58,649: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:58,649: topic[/local_control/goto] removing connection to http://freight1207:35378/
[rospy.internal][ERROR] 2018-12-16 18:54:58,649: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-16 18:54:58,649: Unable to initiate TCP/IP socket to freight1207:35644 (http://freight1207:35378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 18:54:58,649: topic[/local_control/initialpose] removing connection to http://freight1207:35378/
[rospy.internal][INFO] 2018-12-16 18:54:58,650: topic[/remote_control] removing connection to http://freight1207:35378/
[rospy.internal][INFO] 2018-12-16 18:54:58,650: topic[/local_control/cancel] removing connection to http://freight1207:35378/
[rospy.internal][INFO] 2018-12-16 18:54:58,650: topic[/current/pose] removing connection to http://freight1207:52213/
[rospy.internal][INFO] 2018-12-16 18:54:58,650: topic[/current/pose] removing connection to http://freight1207:35378/
[rospy.impl.masterslave][INFO] 2018-12-16 18:54:58,650: atexit
[rosout][INFO] 2018-12-16 18:56:55,958: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-16 18:56:55,958: signal_shutdown [Closing]
[rospy.core][INFO] 2018-12-16 18:56:55,958: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-16 18:57:26,448: init_node, name[/rostful_server], pid[15356]
[xmlrpc][INFO] 2018-12-16 18:57:26,448: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 18:57:26,449: Started XML-RPC server [http://freight1207:33789/]
[rospy.init][INFO] 2018-12-16 18:57:26,449: ROS Slave URI: [http://freight1207:33789/]
[rospy.impl.masterslave][INFO] 2018-12-16 18:57:26,449: _ready: http://freight1207:33789/
[xmlrpc][INFO] 2018-12-16 18:57:26,449: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 18:57:26,450: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 18:57:26,549: registered with master
[rospy.rosout][INFO] 2018-12-16 18:57:26,549: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 18:57:26,551: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 18:57:26,553: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 18:57:26,557: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 18:57:26,833: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-16 18:57:27,604: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-16 18:57:27,615: topic[/current/pose] adding connection to [http://freight1207:40802/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,617: topic[/current/pose] adding connection to [http://freight1207:33789/], count 1
[rospy.internal][INFO] 2018-12-16 18:57:27,618: topic[/remote_control] adding connection to [http://freight1207:33789/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,619: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,620: topic[/enable_software_runstop] adding connection to [http://freight1207:33789/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,621: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,621: topic[/local_control/cancel] adding connection to [http://freight1207:33789/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,622: topic[/local_control/initialpose] adding connection to [http://freight1207:33789/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,623: topic[/local_control/goto] adding connection to [http://freight1207:33789/], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,623: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,624: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,624: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,625: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 18:57:27,644: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2018-12-16 18:57:27,835: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2018-12-16 18:57:27,835: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 18:57:27,835: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 18:58:39,574: topic[/current/pose] adding connection to [/rostopic_15731_1545015519442], count 1
[rospy.internal][WARNING] 2018-12-16 19:00:21,266: Unknown error initiating TCP/IP socket to freight1207:41003 (http://freight1207:40802/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-16 19:00:21,266: topic[/current/pose] removing connection to http://freight1207:40802/
[rospy.client][INFO] 2018-12-16 19:09:11,787: init_node, name[/rostful_server], pid[17708]
[xmlrpc][INFO] 2018-12-16 19:09:11,787: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 19:09:11,787: Started XML-RPC server [http://freight1207:46060/]
[rospy.init][INFO] 2018-12-16 19:09:11,787: ROS Slave URI: [http://freight1207:46060/]
[rospy.impl.masterslave][INFO] 2018-12-16 19:09:11,787: _ready: http://freight1207:46060/
[xmlrpc][INFO] 2018-12-16 19:09:11,788: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 19:09:11,788: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 19:09:11,888: registered with master
[rospy.rosout][INFO] 2018-12-16 19:09:11,888: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 19:09:11,890: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 19:09:11,891: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 19:09:11,894: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 19:09:12,091: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-16 19:09:12,942: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-16 19:09:12,955: topic[/current/pose] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,956: topic[/remote_control] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,957: topic[/enable_software_runstop] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,958: topic[/local_control/cancel] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,959: topic[/local_control/initialpose] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,959: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,960: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,960: topic[/local_control/goto] adding connection to [http://freight1207:46060/], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,961: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,961: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,961: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:12,962: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:09:13,015: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2018-12-16 19:10:07,681: topic[/current/pose] adding connection to [http://freight1207:60410/], count 1
[rospy.internal][INFO] 2018-12-16 19:10:07,869: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 19:10:07,869: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2018-12-16 19:10:07,869: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 19:10:27,993: topic[/remote_control] adding connection to [/remote_control], count 1
[rosout][INFO] 2018-12-16 19:11:51,578: rostful_server: Shutting down the server
[rospy.core][INFO] 2018-12-16 19:11:51,579: signal_shutdown [Closing]
[rospy.internal][INFO] 2018-12-16 19:11:51,582: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 19:11:51,583: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2018-12-16 19:11:51,583: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 19:11:51,584: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2018-12-16 19:11:51,584: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,584: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2018-12-16 19:11:51,584: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,584: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 19:11:51,584: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2018-12-16 19:11:51,585: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 19:11:51,585: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,585: topic[/remote_control] removing connection to /remote_control
[rospy.internal][ERROR] 2018-12-16 19:11:51,585: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,585: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2018-12-16 19:11:51,586: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2018-12-16 19:11:51,586: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2018-12-16 19:11:51,586: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,586: topic[/enable_software_runstop] removing connection to http://freight1207:46060/
[rospy.internal][INFO] 2018-12-16 19:11:51,586: topic[/local_control/goto] removing connection to http://freight1207:46060/
[rospy.internal][ERROR] 2018-12-16 19:11:51,586: Unable to initiate TCP/IP socket to freight1207:42121 (http://freight1207:46060/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-16 19:11:51,586: topic[/local_control/initialpose] removing connection to http://freight1207:46060/
[rospy.internal][INFO] 2018-12-16 19:11:51,587: topic[/remote_control] removing connection to http://freight1207:46060/
[rospy.internal][INFO] 2018-12-16 19:11:51,587: topic[/local_control/cancel] removing connection to http://freight1207:46060/
[rospy.internal][INFO] 2018-12-16 19:11:51,587: topic[/current/pose] removing connection to http://freight1207:46060/
[rospy.internal][INFO] 2018-12-16 19:11:51,587: topic[/current/pose] removing connection to http://freight1207:60410/
[rospy.impl.masterslave][INFO] 2018-12-16 19:11:51,587: Closing
[rospy.core][INFO] 2018-12-16 19:11:51,751: signal_shutdown [atexit]
[rospy.client][INFO] 2018-12-16 19:12:14,787: init_node, name[/rostful_server], pid[17958]
[xmlrpc][INFO] 2018-12-16 19:12:14,788: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-16 19:12:14,788: Started XML-RPC server [http://freight1207:52694/]
[rospy.init][INFO] 2018-12-16 19:12:14,788: ROS Slave URI: [http://freight1207:52694/]
[rospy.impl.masterslave][INFO] 2018-12-16 19:12:14,788: _ready: http://freight1207:52694/
[xmlrpc][INFO] 2018-12-16 19:12:14,788: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-16 19:12:14,789: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-16 19:12:14,888: registered with master
[rospy.rosout][INFO] 2018-12-16 19:12:14,888: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-16 19:12:14,890: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-16 19:12:14,891: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2018-12-16 19:12:14,895: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2018-12-16 19:12:15,129: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2018-12-16 19:12:15,943: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2018-12-16 19:12:15,954: topic[/current/pose] adding connection to [http://freight1207:60410/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,955: topic[/current/pose] adding connection to [http://freight1207:52694/], count 1
[rospy.internal][INFO] 2018-12-16 19:12:15,958: topic[/remote_control] adding connection to [http://freight1207:52694/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,958: topic[/enable_software_runstop] adding connection to [http://freight1207:52694/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,958: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,960: topic[/local_control/initialpose] adding connection to [http://freight1207:52694/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,960: topic[/enable_software_runstop] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,961: topic[/local_control/cancel] adding connection to [http://freight1207:52694/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,961: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,962: topic[/local_control/goto] adding connection to [http://freight1207:52694/], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,962: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,963: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,963: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2018-12-16 19:12:15,970: topic[/enable_software_runstop] adding connection to [/software_runstop], count 1
[rospy.internal][INFO] 2018-12-16 19:12:16,130: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2018-12-16 19:12:16,130: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 19:12:16,130: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2018-12-16 19:12:16,131: topic[/remote_control] adding connection to [/remote_control], count 1
[rosout][WARNING] 2018-12-16 19:16:28,839: publishing data: True to topic /local_control/cancel
[rosout][WARNING] 2018-12-16 19:19:05,521: publishing data: True to topic /local_control/cancel
[rosout][WARNING] 2018-12-16 19:19:25,301: publishing data: True to topic /enable_software_runstop
[rosout][WARNING] 2018-12-16 19:19:30,611: publishing data: False to topic /enable_software_runstop
[rosout][WARNING] 2018-12-16 19:20:01,612: publishing data: False to topic /enable_software_runstop
[rospy.internal][INFO] 2018-12-16 19:42:29,022: topic[/enable_software_runstop] adding connection to [/software_runstop], count 2
[rospy.internal][INFO] 2018-12-16 19:42:29,022: topic[/enable_software_runstop] removing connection to /software_runstop
